import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

from main_window import MainWindow


class FirstWindow(QDialog):
    def __init__(self, dialog):
        super().__init__(dialog)
        dialog.resize(686, 658)
        self.centralwidget = QtWidgets.QWidget(dialog)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 40, 622, 561))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        spacer_item = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacer_item)
        self.LogoQLabel = QtWidgets.QLabel(self.widget)
        self.LogoQLabel.setMaximumSize(QtCore.QSize(300, 300))
        self.LogoQLabel.setAutoFillBackground(False)
        self.LogoQLabel.setText("")
        self.LogoQLabel.setPixmap(QtGui.QPixmap("img/ytu_logo.png"))
        self.LogoQLabel.setScaledContents(True)
        self.horizontalLayout_2.addWidget(self.LogoQLabel)
        spacer_item1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacer_item1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacer_item2 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacer_item2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.CourseQLabel = QtWidgets.QLabel(self.widget)
        font24_bold = QtGui.QFont()
        font24_bold.setPointSize(24)
        font24_bold.setBold(True)
        font24_bold.setWeight(75)
        self.CourseQLabel.setFont(font24_bold)
        self.CourseQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.CourseQLabel)
        self.TermQLabel = QtWidgets.QLabel(self.widget)
        self.TermQLabel.setFont(font24_bold)
        self.TermQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.TermQLabel)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacer_item3 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacer_item3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        spacer_item4 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacer_item4)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setMinimumSize(QtCore.QSize(450, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalLayout_3.addWidget(self.line)
        spacer_item5 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacer_item5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.ProgramQLabel = QtWidgets.QLabel(self.widget)
        font20 = QtGui.QFont()
        font20.setPointSize(20)
        self.ProgramQLabel.setFont(font20)
        self.ProgramQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_2.addWidget(self.ProgramQLabel)
        spacer_item6 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacer_item6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        spacer_item7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacer_item7)
        self.NextQPushButton = QtWidgets.QPushButton(self.widget)
        self.NextQPushButton.setMinimumSize(QtCore.QSize(200, 30))
        self.NextQPushButton.setMaximumSize(QtCore.QSize(200, 90))
        font16 = QtGui.QFont()
        font16.setPointSize(16)
        self.NextQPushButton.setFont(font16)
        self.horizontalLayout.addWidget(self.NextQPushButton)
        spacer_item8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacer_item8)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        dialog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        dialog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dialog)
        dialog.setStatusBar(self.statusbar)

        dialog.setWindowTitle("MainWindow")
        self.CourseQLabel.setText("Big Data Processing and Analytics")
        self.TermQLabel.setText("Term Project")
        self.ProgramQLabel.setText("Amazon Fine Food Reviews")
        self.NextQPushButton.setText("NEXT")

        QtCore.QMetaObject.connectSlotsByName(dialog)

        # self.BrowseQPushButton.clicked.connect(self.browse_file)
        self.NextQPushButton.clicked.connect(self.open_window)

    def open_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = MainWindow(self.window)
        first_window.hide()
        self.window.show()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    first_window = QtWidgets.QMainWindow()
    ui = FirstWindow(first_window)
    first_window.show()
    sys.exit(app.exec_())
