from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QDialog, QApplication

from config import variables
from util.SSH import SSH
from util.HDFS import HDFS

import random


class Ui_MainWindow(QDialog):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1007, 630))
        MainWindow.setMaximumSize(QtCore.QSize(1007, 630))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(21, 29, 962, 558))
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.DatasetQLabel = QtWidgets.QLabel(self.widget)
        self.DatasetQLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.DatasetQLabel.setMaximumSize(QtCore.QSize(90, 95545))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.DatasetQLabel.setFont(font)
        self.DatasetQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DatasetQLabel.setObjectName("DatasetQLabel")
        self.horizontalLayout_8.addWidget(self.DatasetQLabel)
        self.DatasetPathQLineEdit = QtWidgets.QLineEdit(self.widget)
        self.DatasetPathQLineEdit.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.DatasetPathQLineEdit.setFont(font)
        self.DatasetPathQLineEdit.setObjectName("DatasetPathQLineEdit")
        self.horizontalLayout_8.addWidget(self.DatasetPathQLineEdit)
        self.DatasetBrowseQPushButton = QtWidgets.QPushButton(self.widget)
        self.DatasetBrowseQPushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.DatasetBrowseQPushButton.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DatasetBrowseQPushButton.setFont(font)
        self.DatasetBrowseQPushButton.setObjectName("DatasetBrowseQPushButton")
        self.horizontalLayout_8.addWidget(self.DatasetBrowseQPushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.JarQLabel = QtWidgets.QLabel(self.widget)
        self.JarQLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.JarQLabel.setMaximumSize(QtCore.QSize(90, 95545))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.JarQLabel.setFont(font)
        self.JarQLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.JarQLabel.setObjectName("JarQLabel")
        self.horizontalLayout_9.addWidget(self.JarQLabel)
        self.JarPathQLineEdit = QtWidgets.QLineEdit(self.widget)
        self.JarPathQLineEdit.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.JarPathQLineEdit.setFont(font)
        self.JarPathQLineEdit.setObjectName("JarPathQLineEdit")
        self.horizontalLayout_9.addWidget(self.JarPathQLineEdit)
        self.JarBrowseQPushButton = QtWidgets.QPushButton(self.widget)
        self.JarBrowseQPushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.JarBrowseQPushButton.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.JarBrowseQPushButton.setFont(font)
        self.JarBrowseQPushButton.setObjectName("JarBrowseQPushButton")
        self.horizontalLayout_9.addWidget(self.JarBrowseQPushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FunctionsQGroupBox = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FunctionsQGroupBox.setFont(font)
        self.FunctionsQGroupBox.setTitle("")
        self.FunctionsQGroupBox.setObjectName("FunctionsQGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FunctionsQGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.FunctionsQGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.FunctionsQGroupBox)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(431, 0))
        self.label.setMaximumSize(QtCore.QSize(431, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.FunctionsQGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.label_2 = QtWidgets.QLabel(self.FunctionsQGroupBox)
        self.label_2.setMinimumSize(QtCore.QSize(431, 0))
        self.label_2.setMaximumSize(QtCore.QSize(431, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.FunctionsQGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.label_3 = QtWidgets.QLabel(self.FunctionsQGroupBox)
        self.label_3.setMinimumSize(QtCore.QSize(401, 0))
        self.label_3.setMaximumSize(QtCore.QSize(401, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.FunctionsQGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.label_4 = QtWidgets.QLabel(self.FunctionsQGroupBox)
        self.label_4.setMinimumSize(QtCore.QSize(431, 0))
        self.label_4.setMaximumSize(QtCore.QSize(445, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.FunctionsQGroupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.label_5 = QtWidgets.QLabel(self.FunctionsQGroupBox)
        self.label_5.setMinimumSize(QtCore.QSize(381, 0))
        self.label_5.setMaximumSize(QtCore.QSize(381, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.FunctionsQGroupBox)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LiveNodeCountQLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LiveNodeCountQLabel.setFont(font)
        self.LiveNodeCountQLabel.setObjectName("LiveNodeCountQLabel")
        self.verticalLayout_3.addWidget(self.LiveNodeCountQLabel)
        self.MasterLabelQLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.MasterLabelQLabel.setFont(font)
        self.MasterLabelQLabel.setObjectName("MasterLabelQLabel")
        self.verticalLayout_3.addWidget(self.MasterLabelQLabel)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(221, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(5454, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OutputFolderPathQLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.OutputFolderPathQLineEdit.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.OutputFolderPathQLineEdit.setFont(font)
        self.OutputFolderPathQLineEdit.setObjectName("OutputFolderPathQLineEdit")
        self.horizontalLayout_2.addWidget(self.OutputFolderPathQLineEdit)
        self.OutputFolderBrowseQPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.OutputFolderBrowseQPushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.OutputFolderBrowseQPushButton.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OutputFolderBrowseQPushButton.setFont(font)
        self.OutputFolderBrowseQPushButton.setObjectName("OutputFolderBrowseQPushButton")
        self.horizontalLayout_2.addWidget(self.OutputFolderBrowseQPushButton)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.StartServicesQPushButton = QtWidgets.QPushButton(self.widget)
        self.StartServicesQPushButton.setMinimumSize(QtCore.QSize(201, 30))
        self.StartServicesQPushButton.setMaximumSize(QtCore.QSize(201, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.StartServicesQPushButton.setFont(font)
        self.StartServicesQPushButton.setObjectName("StartServicesQPushButton")
        self.horizontalLayout_11.addWidget(self.StartServicesQPushButton)
        self.StopServicesQPushButton = QtWidgets.QPushButton(self.widget)
        self.StopServicesQPushButton.setMinimumSize(QtCore.QSize(201, 30))
        self.StopServicesQPushButton.setMaximumSize(QtCore.QSize(201, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.StopServicesQPushButton.setFont(font)
        self.StopServicesQPushButton.setObjectName("StopServicesQPushButton")
        self.horizontalLayout_11.addWidget(self.StopServicesQPushButton)
        spacerItem = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.StartQPushButton = QtWidgets.QPushButton(self.widget)
        self.StartQPushButton.setMinimumSize(QtCore.QSize(201, 30))
        self.StartQPushButton.setMaximumSize(QtCore.QSize(201, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.StartQPushButton.setFont(font)
        self.StartQPushButton.setObjectName("StartQPushButton")
        self.horizontalLayout_11.addWidget(self.StartQPushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.LogQTextEdt = QtWidgets.QTextEdit(self.widget)
        self.LogQTextEdt.setMinimumSize(QtCore.QSize(750, 250))
        self.LogQTextEdt.setMaximumSize(QtCore.QSize(4564, 250))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.LogQTextEdt.setFont(font)
        self.LogQTextEdt.setObjectName("LogQTextEdt")
        self.verticalLayout_7.addWidget(self.LogQTextEdt)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ##
        self.ssh = SSH()
        self.hdfs = HDFS()

        self.isRunning = False

        self.DatasetBrowseQPushButton.clicked.connect(lambda: self.browse_file("dataset"))
        self.JarBrowseQPushButton.clicked.connect(lambda: self.browse_file("jar"))
        self.OutputFolderBrowseQPushButton.clicked.connect(lambda: self.browse_file("output"))
        self.StartQPushButton.clicked.connect(self.run)
        self.StartServicesQPushButton.clicked.connect(self.start_services)
        self.StopServicesQPushButton.clicked.connect(self.stop_services)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DatasetQLabel.setText(_translate("MainWindow", "Dataset"))
        self.DatasetBrowseQPushButton.setText(_translate("MainWindow", "Browse"))
        self.JarQLabel.setText(_translate("MainWindow", "Jar"))
        self.JarBrowseQPushButton.setText(_translate("MainWindow", "Browse"))
        self.label_6.setText(_translate("MainWindow", "Sum"))
        self.label.setText(_translate("MainWindow", "(review count of each product)"))
        self.label_7.setText(_translate("MainWindow", "Avg"))
        self.label_2.setText(_translate("MainWindow", "(average rating score of each product)"))
        self.label_8.setText(_translate("MainWindow", "Min-Max"))
        self.label_3.setText(_translate("MainWindow", "(the most and least helpful comments)"))
        self.label_9.setText(_translate("MainWindow", "Std"))
        self.label_4.setText(_translate("MainWindow", "(standard deviation of each product scores)"))
        self.label_10.setText(_translate("MainWindow", "Correlation"))
        self.label_5.setText(_translate("MainWindow", "(pearson correlation of helpfulness_ration and scores)"))
        self.groupBox.setTitle(_translate("MainWindow", "Cluster Status"))
        self.LiveNodeCountQLabel.setText(_translate("MainWindow", "Live nodes"))
        self.MasterLabelQLabel.setText(_translate("MainWindow", "Master IP address="))
        self.groupBox_3.setTitle(_translate("MainWindow", "Output Folder"))
        self.OutputFolderBrowseQPushButton.setText(_translate("MainWindow", "Browse"))
        self.StartServicesQPushButton.setText(_translate("MainWindow", "Start Services"))
        self.StopServicesQPushButton.setText(_translate("MainWindow", "Stop Services"))
        self.StartQPushButton.setText(_translate("MainWindow", "Start"))

    def initWidgets(self):
        # Live node count
        command = variables.HADOOP_HOME_PATH + "/bin/hdfs dfsadmin -report"
        result = self.ssh.execute(command)
        matched_lines = [line for line in result.split('\n') if "Live datanodes" in line]
        live_node_count = matched_lines[0].split(':')[0]

        # Master IP address
        command = "cat /etc/hosts"
        result = self.ssh.execute(command)
        matched_lines = [line for line in result.split('\n') if "master" in line]
        master_IP_address = matched_lines[0].split(' ')[0]

        self.LiveNodeCountQLabel.setText(live_node_count)
        self.MasterLabelQLabel.setText("Master IP adress=" + master_IP_address)

    def browse_file(self, id):
        if id == "dataset":
            filenames = QFileDialog.getOpenFileName(self, 'Open File', '/home/osemrt/Desktop')
            firstFile = filenames[0]
            self.DatasetPathQLineEdit.setText(firstFile)
        elif id == "jar":
            filenames = QFileDialog.getOpenFileName(self, 'Open File', '/home/osemrt/Desktop', '*.jar')
            firstFile = filenames[0]
            self.JarPathQLineEdit.setText(firstFile)
        elif id == "output":
            dialog = QFileDialog()
            foo_dir = dialog.getExistingDirectory(self, 'Select  directory')
            self.OutputFolderPathQLineEdit.setText(foo_dir)

    def run(self):
        if (self.isRunning == False):
            self.LogQTextEdt.setText(self.LogQTextEdt.toPlainText() + "\nPlease, start services first!\n")


        else:
            self.change_button_text("Stop")
            start_command = self.get_start_command()
            self.ssh.execute_and_write(self.LogQTextEdt, start_command)

            self.get_file_from_hdfs()

            self.change_button_text("Start")

        QApplication.processEvents()



    def get_start_command(self):
        jar_path = self.JarPathQLineEdit.text()
        dataset_path = self.DatasetPathQLineEdit.text()
        filename_in_hdfs = str(random.randint(0, 1000000))

        dataset_filename = dataset_path.split('/')[-1]
        self.hdfs.copy_file_to_HDFS(dataset_path, "/app/dataset/")
        self.output_location_in_hdfs = "/app/outputs/" + filename_in_hdfs
        return variables.HADOOP_HOME_PATH + "/bin/hadoop" + " jar " + jar_path + " " + "/app/dataset/" + dataset_filename + " " + self.output_location_in_hdfs

    def get_file_from_hdfs(self):
        save_to = self.OutputFolderPathQLineEdit.text()
        self.hdfs.get_file_from_HDFS(self.output_location_in_hdfs, save_to)

    def start_services(self):
        self.StartServicesQPushButton.setText("Stop")
        self.ssh.execute_and_write(self.LogQTextEdt, variables.HADOOP_HOME_PATH + '/sbin/start-all.sh')
        # self.ssh.execute_and_write(self.LogQTextEdt, variables.HADOOP_HOME_PATH + '/sbin/start-dfs.sh')
        # self.ssh.execute_and_write(self.LogQTextEdt, variables.HADOOP_HOME_PATH + '/sbin/start-yarn.sh')
        self.isRunning = True
        self.StartServicesQPushButton.setText("Start Services")
        self.initWidgets()

    def stop_services(self):
        self.StopServicesQPushButton.setText("Stop")
        self.ssh.execute_and_write(self.LogQTextEdt, variables.HADOOP_HOME_PATH + '/sbin/stop-all.sh')
        self.StopServicesQPushButton.setText("Stop Services")
        self.LiveNodeCountQLabel.setText("Live nodes")
        self.MasterLabelQLabel.setText("Master IP address=")

    def change_button_text(self, text):
        self.StartQPushButton.setText(text)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
